project:
  type: book
  output-dir: docs

book:
  title: "Probability & Statistics 101"
  author: "-YY-"
  chapters:
    - index.qmd
    - Ch1.qmd
    # - Ch2.qmd
    # - Ch3.qmd
    # - Ch4.qmd
    # - Ch6.qmd
    # - Ch7.qmd
    # - Ch8.qmd
    # - Ch9.qmd

bibliography: references.bib

format:
  html:
    number-sections: true
    theme:
      - lux
      - custom.scss
  pdf:
    number-sections: true
    documentclass: scrreprt
    toc: true
    lof: true
    lot: true

editor: visual